### ISSUE TITLE
Move x264-sys into a separate repository.

### ISSUE THREAD

**Issue by quadrupleslap** [rust-av/x264-rs#1]

**Comment by lu-zero** [comment]
Normally -sys crates live with the higher-level API crate like in x264-rs, what is the reason to keep the crate in a separate repository? (considering that I'd lose the ability to make atomic changes in the high-level api and the low level one)

**Comment by quadrupleslap** [comment]
This isn't really anything major, but:

1. Why would you want to change the low-level API when it's just bindings?
2. If another crate used just the x264-sys bindings, users would then have to download the rest of the repo, too.
3. Most `sys` crates actually live in their own repositories as far as I'm aware - see `llvm-sys`, `exif-sys`, `libusb-sys`, `core-foundation-sys`, etc.

**Comment by lu-zero** [comment]
- Soon(TM) the x264 upstream will change the API because of the multi-bitdepth support (assuming @kodabb keeps rebasing the patchset), by that time I'll have to rework both the `-sys` crate and higher level bindings.
- cargo.io just have you get the single crate you ask for that I know.
- my reference is `openssl-sys`

Since this project is quite young I'd rather keep everything together for the time being, if there is an additional need to have it spun off it can be made more or less anytime.
