### ISSUE TITLE
x264 [error] Invalid Preset

### ISSUE THREAD

**Issue by aftix** [rust-av/x264-rs#20]
I am trying to make a Param as in the example, using
`let mut par = x264::Param::default_preset("medium", None).unwrap();`
This leads to a thread panic with x264 printing out
`x264 [error]: invalid preset '8졶U'`.
The string is different every time the program runs.

**Comment by lu-zero** [comment]
Seems like that code has an error. Had been a while since I looked at it.

**Comment by naps62** [comment]
I just got this error as well. On further investigation, it's caused by these lines: https://github.com/rust-av/x264-rs/blob/5816190ec33c89cf336636896d21fa783c606970/src/lib.rs#L189-L193

the string is being allocated inside a closure, and only a raw pointer is getting out. This means the string itself ends up being de-allocated before even being used.
